# Generated by Django 5.0.3 on 2024-12-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
