# Generated by Django 5.0.3 on 2024-12-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_collaboration_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collaboration',
            table='collaboration',
        ),
    ]
