# Generated by Django 5.0 on 2024-12-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_collaboration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='foto',
            field=models.ImageField(default=False, upload_to='media/categories/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='foto',
            field=models.ImageField(default=False, null=True, upload_to='media/content/'),
        ),
    ]
